### ISSUE TITLE
trim() expects parameter 1 to be string, array given (sheet.php:179)

### ISSUE THREAD

**Issue by 14rynx** [ikkez/f3-sheet#1]
While trying to export some tables from https://github.com/exodus4d/pathfinder I have encountered a bug while exporting a table using the dumpCSV function. 

    trim() expects parameter 1 to be string, array given (sheet.php:179)

The Issue seems to be that for whatever reason my input has an array in a non-header field (Not sure if that is an intended way of use), which results in an error as the trim function doesn't deal with arrays.

I propose moving the trim(function) into it's own if clause, so that it only gets called when necessary:
    
```php
elseif (isset($rows[$i-1][$ckey])) 
        $field = $rows[$i-1][$ckey];
if (is_string($field))
        $field = trim($field);
```
I think the same Issue might also occur in the dumpXLS function where there is a similar section of code, but I haven't tried it.

**Comment by ikkez** [comment]
absolutely right. fixed in v0.4.2
