### ISSUE TITLE
Why force UTF-16LE encoding?

### ISSUE THREAD

**Issue by ethanpil** [ikkez/f3-sheet#4]
Spent a long time trying to figure out what's wrong on my server until I found UTF-16LE hardcoded into the CSV output. 
What do you think about making this optional?

I'm thinking we can make a property on the object with the default `UTF-16LE` something like this:

````
class Sheet extends \Prefab {

     public $encoding = 'UTF-16LE';

...
````

Later we can change as needed

````
$csv = \Sheet::instance();
$csv->encoding = 'UTF8';
...
````

and then in `renderCSV()` we can encode based on that value...

**Comment by ethanpil** [comment]
I can submit a PR if you would like.... If I do I might try sneaking in `UTF8` as the default... Let me know what you think...

**Comment by ikkez** [comment]
I think that it was some quirks with an old MS Excel version where you were not able to open a CSV file that was exported in UTF8 only. But I guess it's fine to change now.

**Comment by ikkez** [comment]
fixed in latest commit / release
